"use client"

import { useMemo, useState } from "react"
import { Box, CalendarPlus, MapPin, Search, SlidersHorizontal } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { machines, type Machine } from "@/lib/portal-data"

function BookingDialog({ machine }: { machine: Machine }) {
  const [submitted, setSubmitted] = useState(false)
  return <Dialog onOpenChange={(open) => { if (!open) setSubmitted(false) }}><DialogTrigger asChild><Button disabled={machine.status === "maintenance"}>Reserve<CalendarPlus data-icon="inline-end" /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{submitted ? "Request received" : `Reserve ${machine.name}`}</DialogTitle><DialogDescription>{submitted ? "Faculty review has been notified. Track progress in Bookings." : "Select a supervised lab window and tell the operator what you are making."}</DialogDescription></DialogHeader>{submitted ? <div className="rounded-lg border bg-secondary p-5"><p className="font-mono text-xs uppercase text-muted-foreground">Request / BK-1052</p><p className="mt-2 font-medium">Pending faculty approval</p></div> : <form id={`booking-${machine.id}`} className="flex flex-col gap-4" onSubmit={(event) => { event.preventDefault(); setSubmitted(true) }}><div className="flex flex-col gap-2"><Label htmlFor={`date-${machine.id}`}>Date</Label><Input id={`date-${machine.id}`} type="date" required /></div><div className="flex flex-col gap-2"><Label>Start time</Label><Select required><SelectTrigger><SelectValue placeholder="Select an available window" /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="0930">09:30–11:30</SelectItem><SelectItem value="1300">13:00–15:00</SelectItem><SelectItem value="1600">16:00–18:00</SelectItem></SelectGroup></SelectContent></Select></div><div className="flex flex-col gap-2"><Label htmlFor={`purpose-${machine.id}`}>Purpose</Label><Textarea id={`purpose-${machine.id}`} placeholder="Project, material, and intended outcome" required /></div></form>}<DialogFooter>{!submitted && <Button type="submit" form={`booking-${machine.id}`}>Submit request</Button>}</DialogFooter></DialogContent></Dialog>
}

export function MachineCatalog() {
  const [query, setQuery] = useState("")
  const [process, setProcess] = useState("all")
  const visible = useMemo(() => machines.filter((machine) => (process === "all" || machine.process === process) && `${machine.name} ${machine.model} ${machine.material}`.toLowerCase().includes(query.toLowerCase())), [query, process])

  return <div className="flex flex-col gap-8"><div className="border-b pb-8"><p className="font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">Equipment registry / live</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Machine floor</h2><p className="mt-2 max-w-2xl text-muted-foreground">Find qualified equipment, check its live condition, and start a supervised booking request.</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search machine, process, or material" className="pl-9" aria-label="Search machines" /></div><Select value={process} onValueChange={setProcess}><SelectTrigger className="w-full sm:w-52"><SlidersHorizontal /><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="all">All processes</SelectItem><SelectItem value="FDM">FDM</SelectItem><SelectItem value="Resin">Resin</SelectItem><SelectItem value="Powder">Powder</SelectItem><SelectItem value="Metal FFF">Metal FFF</SelectItem></SelectGroup></SelectContent></Select></div><div className="grid gap-4 md:grid-cols-2">{visible.map((machine) => <Card key={machine.id} className="overflow-hidden"><div className="flex h-36 items-center justify-center border-b bg-secondary"><Box className="size-16 stroke-[1] text-muted-foreground" /></div><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle>{machine.name}</CardTitle><CardDescription>{machine.model} · {machine.process}</CardDescription></div><Badge variant={machine.status === "available" ? "default" : machine.status === "in-use" ? "secondary" : "destructive"}>{machine.status}</Badge></div></CardHeader><CardContent className="grid grid-cols-2 gap-4 font-mono text-xs"><div><p className="text-muted-foreground">Material</p><p className="mt-1">{machine.material}</p></div><div><p className="text-muted-foreground">Utilization</p><p className="mt-1">{machine.utilization}%</p></div><div className="col-span-2 flex items-center gap-2 text-muted-foreground"><MapPin className="size-3.5" />{machine.location}</div></CardContent><CardFooter className="justify-between"><Button variant="ghost">View specification</Button><BookingDialog machine={machine} /></CardFooter></Card>)}</div></div>
}
